[ODS-5775] Github actions in forked repositories (#104)
* Check for Azure token on Ed-Fi repositories

* Annotate error messages

diff --git a/Ed-Fi-Extensions/Ed-Fi-Extensions/.github/workflows/Pkg EdFi.Ods.Extensions.Homograph.yml b/Ed-Fi-Extensions/Ed-Fi-Extensions/.github/workflows/Pkg EdFi.Ods.Extensions.Homograph.yml
--- a/Ed-Fi-Extensions/Ed-Fi-Extensions/.github/workflows/Pkg EdFi.Ods.Extensions.Homograph.yml
+++ b/Ed-Fi-Extensions/Ed-Fi-Extensions/.github/workflows/Pkg EdFi.Ods.Extensions.Homograph.yml
@@ -27,6 +27,7 @@ env:
   HEAD_REF:  ${{ GITHUB.HEAD_REF }}
   REF_NAME:  ${{ GITHUB.REF_NAME }}
   REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}
+  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
   build:
@@ -34,6 +35,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check for Azure token
+      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+      run: | 
+        echo "::error::Missing Azure Token"
+        exit 1 
     - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
       run:  echo "${{ github.event.inputs.distinct_id }}"    
     - name: Setup .NET
@@ -104,6 +110,7 @@ jobs:
         .\build.githubactions.ps1 InstallCredentialHandler
       shell: pwsh     
     - name: publish
+      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       working-directory: ./Ed-Fi-Extensions/
       shell: pwsh
       run: |
diff --git a/Ed-Fi-Extensions/Ed-Fi-Extensions/.github/workflows/Pkg EdFi.Ods.Profiles.Sample.yml b/Ed-Fi-Extensions/Ed-Fi-Extensions/.github/workflows/Pkg EdFi.Ods.Profiles.Sample.yml
--- a/Ed-Fi-Extensions/Ed-Fi-Extensions/.github/workflows/Pkg EdFi.Ods.Profiles.Sample.yml
+++ b/Ed-Fi-Extensions/Ed-Fi-Extensions/.github/workflows/Pkg EdFi.Ods.Profiles.Sample.yml
@@ -21,6 +21,7 @@ env:
   HEAD_REF:  ${{ GITHUB.HEAD_REF }}
   REF_NAME:  ${{ GITHUB.REF_NAME }}
   REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}
+  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
   build:
@@ -28,6 +29,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check for Azure token
+      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+      run: | 
+        echo "::error::Missing Azure Token"
+        exit 1   
     - name: Setup .NET
       uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # v2.1.0
       with:
@@ -85,6 +91,7 @@ jobs:
         .\build.githubactions.ps1 InstallCredentialHandler
       shell: pwsh     
     - name: publish
+      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       working-directory: ./Ed-Fi-Extensions/
       shell: pwsh
       run: |
