Adjust all GitHub Actions workflows to stop using the ODS-Implementation repository

diff --git a/.github/workflows/Cleanup Caches by a branch.yml b/.github/workflows/Cleanup Caches by a branch.yml
--- a/.github/workflows/Cleanup Caches by a branch.yml
+++ b/.github/workflows/Cleanup Caches by a branch.yml
@@ -6,9 +6,9 @@
 name: Cleanup Caches by a branch
 on:
   pull_request:
-    branches: [main, 'b-v*-patch*','feature-*']
-    types: [ closed ]
-  
+    branches: [main, "b-v*-patch*", "feature-*"]
+    types: [closed]
+
 permissions: read-all
 
 env:
@@ -21,20 +21,22 @@ jobs:
     steps:
       - name: Check for Repo Dispatch Token
         if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.GH_TOKEN == '' }}
-        run: | 
+        run: |
           echo "::error::Missing GitHub Token"
-          exit 1 
+          exit 1
+
       - name: Check out code
         if: ${{ env.GH_TOKEN != '' }}
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
       - name: Cleanup
         run: |
           gh extension install actions/gh-actions-cache
-          
+
           REPO=${{ github.repository }}
           PULLREQUESTBRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"
-          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $PULLREQUESTBRANCH | cut -f 1 )          
-          ## Setting this to not fail the workflow while deleting cache keys. 
+          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $PULLREQUESTBRANCH | cut -f 1 )
+          ## Setting this to not fail the workflow while deleting cache keys.
           set +e
           echo "Deleting caches for  PULLREQUESTBRANCH $PULLREQUESTBRANCH..."
           for cacheKey in $cacheKeysForPR
@@ -42,7 +44,7 @@ jobs:
               gh actions-cache delete $cacheKey -R $REPO -B $PULLREQUESTBRANCH --confirm
           done
 
-          WORKINGBRANCH=${{ GITHUB.HEAD_REF }}         
+          WORKINGBRANCH=${{ GITHUB.HEAD_REF }}
           echo "HEAD_REF: " ${{ GITHUB.HEAD_REF }}
           echo "REF_NAME: " ${{ GITHUB.REF_NAME }}
           echo "Fetching list of cache key"
@@ -52,5 +54,5 @@ jobs:
           for cacheKey in $cacheKeysForPR
           do
               gh actions-cache delete $cacheKey -R $REPO -B $WORKINGBRANCH --confirm
-          done          
+          done
           echo "Done"
diff --git a/.github/workflows/Lib edFi.admin.dataaccess.yml b/.github/workflows/Lib edFi.admin.dataaccess.yml
--- a/.github/workflows/Lib edFi.admin.dataaccess.yml
+++ b/.github/workflows/Lib edFi.admin.dataaccess.yml
@@ -1,5 +1,5 @@
-# When to Use : 
-   # 1.At the time of  every major/minor version new development must run to get new major/minor version updated in Azure Artifacts 
+# When to Use :
+   # 1.At the time of  every major/minor version new development must run to get new major/minor version updated in Azure Artifacts
    # 2.If any new public method get added/modified in Repository class of Ed-Fi-ODS\Application\EdFi.Admin.DataAccess project which interacts with EdFi_Admin Database.
    # 3.If any .NET new major/minor version upgrade or Nuget package version upgrade happens in Ed-Fi-ODS\Application\EdFi.Admin.DataAccess project
 
@@ -31,57 +31,66 @@ jobs:
     runs-on: ubuntu-24.04
 
     steps:
+
     - name: Check for Azure token
       if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
-      run: | 
-        echo "::error::Missing Azure Token" 
-        exit 1 
+      run: |
+        echo "::error::Missing Azure Token"
+        exit 1
+
     - name: Checkout Ed-Fi-ODS
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      with:
-        repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
-    - name: Cache Nuget packages       
+
+    - name: Cache Nuget packages
       uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2
       with:
         path: ~/.nuget/packages
         key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*', '**/configuration.packages.json') }}
         restore-keys: |
           ${{ runner.os }}-nuget-
-    - name: update BUILD_INCREMENTER 
-      run: |      
+
+    - name: update BUILD_INCREMENTER
+      run: |
             $newRevision = ([int]${{ github.run_number }}) + ([int]${{env.BUILD_INCREMENTER}})
             if ($newRevision -lt 0) {
                 $newRevision = 1
                 echo "BUILD_INCREMENTER=$newRevision">> $env:GITHUB_ENV
             }
       shell: pwsh
+
     - name: Restore NuGet packages
       run: |
         .\build.githubactions.ps1 restore -Solution "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.sln"
-      shell: pwsh                
+      shell: pwsh
+
     - name: build
       run: |
         .\build.githubactions.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -Solution "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.sln" -ProjectFile "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj"
       shell: pwsh
+
     - name: Run Unit tests
       run: |
         .\build.githubactions.ps1 test -Configuration ${{ env.CONFIGURATION }} -Solution "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.sln" -ProjectFile "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj" -TestFilter "DataAccessIntegrationTests"
       shell: pwsh
+
     - name: pack
       run: |
         .\build.githubactions.ps1 pack -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -Solution "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.sln" -ProjectFile "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj" -PackageName  "EdFi.Suite3.Admin.DataAccess"
       shell: pwsh
+
     - name: Install-credential-handler
       if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
-      
+
       run: |
         .\build.githubactions.ps1 InstallCredentialHandler
-      shell: pwsh 
+      shell: pwsh
+
     - name: publish
       if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
       run: |
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -Solution "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.sln" -ProjectFile "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj" -PackageName  "EdFi.Suite3.Admin.DataAccess"
-      shell: pwsh      
+      shell: pwsh
+
     - name: Upload EdFi.Suite3.Admin.DataAccess Artifacts
       if: success()
       uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
diff --git a/.github/workflows/Lib edFi.loadtools.yml b/.github/workflows/Lib edFi.loadtools.yml
--- a/.github/workflows/Lib edFi.loadtools.yml
+++ b/.github/workflows/Lib edFi.loadtools.yml
@@ -1,5 +1,5 @@
-# When to Use : 
-   # 1.At the time of every major/minor version new development must run to get new major/minor version updated in Azure Artifacts 
+# When to Use :
+   # 1.At the time of every major/minor version new development must run to get new major/minor version updated in Azure Artifacts
    # 2.If any new code changes in Utilities/DataLoading/ folder which interacts with BulkLoadClient /SmokeTest.Console tools for testing the ODS/API solution.
    # 3.If any .NET new major/minor version upgrade or Nuget package version upgrade happens in Utilities/DataLoading/LoadTools.sln solution
 
@@ -31,69 +31,80 @@ jobs:
     runs-on: ubuntu-24.04
 
     steps:
+
     - name: Check for Azure token
       if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
-      run: | 
-        echo "::error::Missing Azure Token" 
-        exit 1 
+      run: |
+        echo "::error::Missing Azure Token"
+        exit 1
+
     - name: Checkout Ed-Fi-ODS
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      with:
-        repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
-    - name: Cache Nuget packages       
+
+    - name: Cache Nuget packages
       uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2
       with:
         path: ~/.nuget/packages
         key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*', '**/configuration.packages.json') }}
         restore-keys: |
           ${{ runner.os }}-nuget-
-    - name: update BUILD_INCREMENTER 
-      run: |      
+
+    - name: update BUILD_INCREMENTER
+      run: |
             $newRevision = ([int]${{ github.run_number }}) + ([int]${{env.BUILD_INCREMENTER}})
             if ($newRevision -lt 0) {
                 $newRevision = 1
                 echo "BUILD_INCREMENTER=$newRevision">> $env:GITHUB_ENV
             }
       shell: pwsh
+
     - name: Restore NuGet packages
       run: |
         .\build.githubactions.ps1 restore -Solution "Utilities/DataLoading/LoadTools.sln"
       shell: pwsh
+
     - name: build
       run: |
         .\build.githubactions.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -Solution "Utilities/DataLoading/LoadTools.sln"
       shell: pwsh
+
     - name: Run Unit tests
       run: |
         .\build.githubactions.ps1 test -Configuration ${{ env.CONFIGURATION }} -Solution "Utilities/DataLoading/LoadTools.sln" -TestFilter "RunManually"
       shell: pwsh
+
     - name: pack load tools
       run: |
         .\build.githubactions.ps1 pack -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj" -PackageName "EdFi.Suite3.LoadTools"
       shell: pwsh
+
     - name: pack bulk load client
       run: |
         .\build.githubactions.ps1 pack -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj" -PackageName "EdFi.Suite3.BulkLoadClient.Console"
       shell: pwsh
+
     - name: pack smoke test console
       run: |
         .\build.githubactions.ps1 pack -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj" -PackageName "EdFi.Suite3.SmokeTest.Console"
-      shell: pwsh          
+      shell: pwsh
+
     - name: Install-credential-handler
       if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
       run: |
         .\build.githubactions.ps1 InstallCredentialHandler
       shell: pwsh
+
     - name: publish load tools,bulk load client & smoke test console
       if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
       run: |
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Ed-Fi-ODS/Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj"  -PackageName "EdFi.Suite3.LoadTools"
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Ed-Fi-ODS/Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj" -PackageName "EdFi.Suite3.BulkLoadClient.Console"
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Ed-Fi-ODS/Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj" -PackageName "EdFi.Suite3.SmokeTest.Console"
-      shell: pwsh      
+      shell: pwsh
+
     - name: Upload EdFi.LoadTools Artifacts
       if: success()
       uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
       with:
         name: NugetPackages.Artifacts
-        path: ${{ github.workspace }}/NugetPackages/*.nupkg      
+        path: ./NugetPackages/*.nupkg
diff --git a/.github/workflows/Lib edFi.ods.standard.yml b/.github/workflows/Lib edFi.ods.standard.yml
--- a/.github/workflows/Lib edFi.ods.standard.yml
+++ b/.github/workflows/Lib edFi.ods.standard.yml
@@ -1,13 +1,13 @@
 # When to Use :
-   # 1.At the time of  every major/minor version new development must run to get new major/minor version updated in Azure Artifacts
-   # 2.If any new database changes which related to ODS Core Standard in /Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj which interacts with EDFI_ODS Database.
-   # 3.If any .NET new major/minor version upgrade or Nuget package version upgrade happens in Ed-Fi-ODS/Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj  Project.
+# 1.At the time of  every major/minor version new development must run to get new major/minor version updated in Azure Artifacts
+# 2.If any new database changes which related to ODS Core Standard in /Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj which interacts with EDFI_ODS Database.
+# 3.If any .NET new major/minor version upgrade or Nuget package version upgrade happens in Ed-Fi-ODS/Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj  Project.
 
 name: Lib EdFi.Ods.Standard
 
 on:
   pull_request:
-    branches: [main, 'b-v*-patch*','feature-*']
+    branches: [main, "b-v*-patch*", "feature-*"]
   workflow_dispatch:
 
 permissions: read-all
@@ -22,9 +22,9 @@ env:
   CONFIGURATION: "Release"
   AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
   AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
-  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
-  HEAD_REF:  ${{ GITHUB.HEAD_REF }}
-  REF_NAME:  ${{ GITHUB.REF_NAME }}
+  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
+  HEAD_REF: ${{ GITHUB.HEAD_REF }}
+  REF_NAME: ${{ GITHUB.REF_NAME }}
   REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}
   REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
@@ -42,83 +42,75 @@ jobs:
         ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
     name: build (Standard ${{ matrix.StandardVersion }} Extension ${{ matrix.ExtensionVersion }})
     steps:
-    - name: Check for Azure token
-      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
-      run: |
-        echo "::error::Missing Azure Token"
-        exit 1
-    - name: Checkout Ed-Fi-ODS
-      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      with:
-        repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
-        path: Ed-Fi-ODS/
-    - name: Checkout Ed-Fi-ODS
-      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      with:
-        repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
-        path: Ed-FI-ODS/
-    - name: Is pull request branch exists in Get-RepositoryRoot "Ed-Fi-ODS"
-      working-directory: ./Ed-Fi-ODS/
-      shell: pwsh
-      run: |
-        .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath ""
-    - name: Cache Nuget packages
-      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2
-      with:
-        path: ~/.nuget/packages
-        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*', '**/configuration.packages.json') }}
-        restore-keys: |
-          ${{ runner.os }}-nuget-
-    - name: update BUILD_INCREMENTER
-      run: |
-            $newRevision = ([int]${{ github.run_number }}) + ([int]${{env.BUILD_INCREMENTER}})
-            if ($newRevision -lt 0) {
-                $newRevision = 1
-                echo "BUILD_INCREMENTER=$newRevision">> $env:GITHUB_ENV
-            }
-      shell: pwsh
-    - name: Restore NuGet packages
-      working-directory: ./Ed-Fi-ODS/
-      run: |
-        .\build.githubactions.ps1 restore -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"
-      shell: pwsh
-    - name: CodeGen
-      shell: pwsh
-      run: |
+      - name: Check for Azure token
+        if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+        run: |
+          echo "::error::Missing Azure Token"
+          exit 1
+
+      - name: Checkout Ed-Fi-ODS
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+      - name: Cache Nuget packages
+        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2
+        with:
+          path: ~/.nuget/packages
+          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*', '**/configuration.packages.json') }}
+          restore-keys: |
+            ${{ runner.os }}-nuget-
+
+      - name: update BUILD_INCREMENTER
+        run: |
+          $newRevision = ([int]${{ github.run_number }}) + ([int]${{env.BUILD_INCREMENTER}})
+          if ($newRevision -lt 0) {
+              $newRevision = 1
+              echo "BUILD_INCREMENTER=$newRevision">> $env:GITHUB_ENV
+          }
+        shell: pwsh
+
+      - name: Restore NuGet packages
+        run: |
+          .\build.githubactions.ps1 restore -ProjectFile "./Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"
+        shell: pwsh
+
+      - name: CodeGen
+        shell: pwsh
+        run: |
           $ErrorActionPreference = 'Stop'
           $PSVersionTable
-          . $env:GITHUB_WORKSPACE/Get-RepositoryRoot "Ed-Fi-ODS"/Initialize-PowershellForDevelopment.ps1
-          Invoke-CodeGen -Engine SQLServer -RepositoryRoot $env:GITHUB_WORKSPACE/ -StandardVersion ${{ matrix.StandardVersion }} -ExtensionVersion ${{ matrix.ExtensionVersion }}
-    - name: build
-      working-directory: ./Ed-Fi-ODS/
-      run: |
-        .\build.githubactions.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}}  -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"   -StandardVersion ${{ matrix.StandardVersion }}
-      shell: pwsh
-    - name: Run Unit tests
-      working-directory: ./Ed-Fi-ODS/
-      run: |
-        .\build.githubactions.ps1 test -Configuration ${{ env.CONFIGURATION }}  -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"
-      shell: pwsh
-    - name: pack
-      working-directory: ./Ed-Fi-ODS/
-      run: |
-        .\build.githubactions.ps1 pack -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}}  -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj" -PackageName  "EdFi.Suite3.Ods.Standard.${{ matrix.StandardVersion }}"
-      shell: pwsh
-    - name: Install-credential-handler
-      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
-      working-directory: ./Ed-Fi-ODS/
-      run: |
-        .\build.githubactions.ps1 InstallCredentialHandler
-      shell: pwsh
-    - name: publish
-      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
-      working-directory: ./Ed-Fi-ODS/
-      run: |
-        .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj" -PackageName  "EdFi.Suite3.Ods.Standard.${{ matrix.StandardVersion }}"
-      shell: pwsh
-    - name: Upload EdFi.Ods.Standard Artifacts
-      if: success()
-      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
-      with:
-        name: NugetPackages.Artifacts-${{ matrix.StandardVersion }}
-        path: ${{ github.workspace }}/Ed-Fi-ODS/NugetPackages/EdFi.Suite3.Ods.Standard.*.nupkg
+          . ./Ed-Fi-ODS/Initialize-PowershellForDevelopment.ps1
+          Invoke-CodeGen -Engine SQLServer -RepositoryRoot ./ -StandardVersion ${{ matrix.StandardVersion }} -ExtensionVersion ${{ matrix.ExtensionVersion }}
+
+      - name: build
+        run: |
+          .\build.githubactions.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}}  -ProjectFile "./Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"   -StandardVersion ${{ matrix.StandardVersion }}
+        shell: pwsh
+
+      - name: Run Unit tests
+        run: |
+          .\build.githubactions.ps1 test -Configuration ${{ env.CONFIGURATION }}  -ProjectFile "./Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"
+        shell: pwsh
+
+      - name: pack
+        run: |
+          .\build.githubactions.ps1 pack -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}}  -ProjectFile "./Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj" -PackageName  "EdFi.Suite3.Ods.Standard.${{ matrix.StandardVersion }}"
+        shell: pwsh
+
+      - name: Install-credential-handler
+        if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
+        run: |
+          .\build.githubactions.ps1 InstallCredentialHandler
+        shell: pwsh
+
+      - name: publish
+        if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
+        run: |
+          .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -ProjectFile "./Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj" -PackageName  "EdFi.Suite3.Ods.Standard.${{ matrix.StandardVersion }}"
+        shell: pwsh
+
+      - name: Upload EdFi.Ods.Standard Artifacts
+        if: success()
+        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
+        with:
+          name: NugetPackages.Artifacts-${{ matrix.StandardVersion }}
+          path: ./Ed-Fi-ODS/NugetPackages/EdFi.Suite3.Ods.Standard.*.nupkg
