[ODS-5775] Allow GitHub actions to run in forked repositories without secrets (#689)
* Allow github actions to succeed without publishing artifacts. Check for existance of Azure tokens on Ed-Fi-Alliance-OSS repositories

* Allow github actions to succeed without repo dispatch tokens

* Annotate error messages

diff --git a/.github/workflows/Cleanup Caches by a branch.yml b/.github/workflows/Cleanup Caches by a branch.yml
--- a/.github/workflows/Cleanup Caches by a branch.yml
+++ b/.github/workflows/Cleanup Caches by a branch.yml
@@ -8,12 +8,22 @@ on:
   pull_request:
     branches: [main, 'ODS-*']
     types: [ closed ]
+  
+env:
+  GH_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
+  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
   cleanup:
     runs-on: ubuntu-latest
     steps:
+      - name: Check for Repo Dispatch Token
+        if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.GH_TOKEN == '' }}
+        run: | 
+          echo "::error::Missing GitHub Token"
+          exit 1 
       - name: Check out code
+        if: ${{ env.GH_TOKEN != '' }}
         uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2
       - name: Cleanup
         run: |
@@ -42,5 +52,3 @@ jobs:
               gh actions-cache delete $cacheKey -R $REPO -B $WORKINGBRANCH --confirm
           done          
           echo "Done"
-        env:
-          GH_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
diff --git a/.github/workflows/Lib edFi.loadtools manual.yml b/.github/workflows/Lib edFi.loadtools manual.yml
--- a/.github/workflows/Lib edFi.loadtools manual.yml
+++ b/.github/workflows/Lib edFi.loadtools manual.yml
@@ -15,6 +15,7 @@ env:
   AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
   AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
   VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
+  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
   build:
@@ -22,6 +23,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check for Azure token
+      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+      run: | 
+        echo "::error::Missing Azure Token" 
+        exit 1 
     - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
     - name: Setup .NET
       uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # 2.1.0
@@ -68,14 +74,17 @@ jobs:
         .\build.githubactions.ps1 InstallCredentialHandler
       shell: pwsh
     - name: publish load tools
+      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       run: |
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Ed-Fi-ODS/Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj"  -PackageName "EdFi.Suite3.LoadTools"
       shell: pwsh      
     - name: publish bulk load client
+      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       run: |
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Ed-Fi-ODS/Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj" -PackageName "EdFi.Suite3.BulkLoadClient.Console"
       shell: pwsh
     - name: publish smoke test console
+      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       run: |
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -Solution "Utilities/DataLoading/LoadTools.sln" -ProjectFile "Ed-Fi-ODS/Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj" -PackageName "EdFi.Suite3.SmokeTest.Console"
       shell: pwsh
