Fix a copy paste error

diff --git a/.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml b/.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
--- a/.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
+++ b/.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
@@ -62,22 +62,22 @@ jobs:
     steps:
     - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
       run:  echo "${{ github.event.inputs.distinct_id }}"
-     
+
     - name: Check for Azure token
       if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
-      run: | 
-        echo "::error::Missing Azure Token" 
-        exit 1 
+      run: |
+        echo "::error::Missing Azure Token"
+        exit 1
     - name: Checkout Ed-Fi-ODS
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       with:
           repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
           path: Ed-Fi-ODS/
-    - name: Checkout Get-RepositoryRoot "Ed-Fi-ODS"
+    - name: Checkout Ed-Fi-ODS
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       with:
-          repository: Ed-Fi-Alliance-OSS/Get-RepositoryRoot "Ed-Fi-ODS"
-          path: Get-RepositoryRoot "Ed-Fi-ODS"/
+          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
+          path: Ed-FI-ODS/
     - name: Set Ed-Fi-Standard Reference
       working-directory: ./Ed-Fi-ODS/
       run: |
@@ -109,8 +109,8 @@ jobs:
         sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
         sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
         sudo apt-get update
-        sudo apt-get -y install postgresql-client-16=16.11-1.pgdg24.04+1   
-    - name: Cache Nuget packages       
+        sudo apt-get -y install postgresql-client-16=16.11-1.pgdg24.04+1
+    - name: Cache Nuget packages
       uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2
       with:
         path: ~/.nuget/packages
@@ -122,8 +122,8 @@ jobs:
       run: |
         .\build.githubactions.ps1 restore -Solution "$env:GITHUB_WORKSPACE/Get-RepositoryRoot "Ed-Fi-ODS"/Application/Ed-Fi-Ods.sln"
       shell: pwsh
-    - name: update BUILD_INCREMENTER 
-      run: |      
+    - name: update BUILD_INCREMENTER
+      run: |
             $newRevision = ([int]${{ github.run_number }}) + ([int]${{env.BUILD_INCREMENTER}})
             if ($newRevision -lt 0) {
                 $newRevision = 1
@@ -149,7 +149,7 @@ jobs:
         } else {
             Write-Host "No Plug-in Extensions found. Skipping removal."
         }
-      shell: pwsh 
+      shell: pwsh
     - name: Create Database Template (no extensions)
       working-directory: ./
       run: |
@@ -168,8 +168,8 @@ jobs:
       working-directory: ./Ed-Fi-ODS/
       run: |
         .\build.githubactions.ps1 InstallCredentialHandler
-      shell: pwsh     
-    - name: publish 
+      shell: pwsh
+    - name: publish
       working-directory: ./Ed-Fi-ODS/
       if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
       run: |
@@ -182,11 +182,11 @@ jobs:
         name: NugetPackages.Artifacts-${{ matrix.StandardVersion }}
         path: ${{ github.workspace }}/Ed-Fi-ODS/NugetPackages/EdFi.Suite3.Ods.Minimal.Template.PostgreSQL*.nupkg
     - name: Move Log Files
-      if: success() || failure()    
+      if: success() || failure()
       run: |
         $bulkLoadClientSourcePath = "${{ github.workspace }}/Ed-Fi-ODS/Utilities/DataLoading/EdFi.BulkLoadClient.Console/bin/${{ env.CONFIGURATION }}/net8.0/logfile.txt"
         $testHarnessSourcePath = "${{ github.workspace }}/Get-RepositoryRoot "Ed-Fi-ODS"/Application/EdFi.Ods.Api.IntegrationTestHarness/bin/${{ env.CONFIGURATION }}/net8.0/TestHarnessLog.log"
-        $testHarnessRequestResponseDetailsSourcePath = "${{ github.workspace }}/Get-RepositoryRoot "Ed-Fi-ODS"/Application/EdFi.Ods.Api.IntegrationTestHarness/bin/${{ env.CONFIGURATION }}/net8.0/TestHarnessRequestResponseDetailsLog.log"        
+        $testHarnessRequestResponseDetailsSourcePath = "${{ github.workspace }}/Get-RepositoryRoot "Ed-Fi-ODS"/Application/EdFi.Ods.Api.IntegrationTestHarness/bin/${{ env.CONFIGURATION }}/net8.0/TestHarnessRequestResponseDetailsLog.log"
         $destinationPath = "${{ github.workspace }}/CreateDatabaseTemplateLogs/"
         # Create the destination folder if it doesn't exist
         if (!(Test-Path -Path $destinationPath)) {
@@ -195,7 +195,7 @@ jobs:
         # Move the files
         Move-Item -Path $bulkLoadClientSourcePath -Destination $destinationPath -Force
         Move-Item -Path $testHarnessSourcePath -Destination $destinationPath -Force
-        Move-Item -Path $testHarnessRequestResponseDetailsSourcePath -Destination $destinationPath -Force           
+        Move-Item -Path $testHarnessRequestResponseDetailsSourcePath -Destination $destinationPath -Force
       shell: pwsh
     - name: Upload Create Database Template Logs
       if: success() || failure()
