[ODS-5714] [ODS-5813] Merge ODS-5714 feature branch to main (#702)
* [ODS-5718] Reorganize Ed-Fi Standard and Extension Artifacts using version-based folder structure (#650)

* Reorganized folder structure

* Added StandardVersion and ExtensionVersion params and providers

* Applied changes to build artifacts on new folder structure

* Updated approval and failing tests

* [ODS-5745] ResourceClaimMetadata changes for multi-version support (#684)

* Fixed tests after rebasing main with epic branch (ODS-5714)

* Split 0001-ResourceClaimMetadata_generated.sql for MsSQL

* Split 0001-ResourceClaimMetadata_generated.sql for PgSQL

* Merged, and moved security scripts to EdFi.Ods.Standard project

* Merged and moved pgsql scripts to EdFi.Ods.Standard project

* Add step to install xsel

* Reverts installation of xsel

* Fixed error in build using linux images

* Fixed wrong claim set name

* Fixed failing test

* [ODS-5770] Update versionmap.json when new standard is released (#687)

* Added version map file

* Add helper script to get standard versions, and repo mappings

* [ODS-5765] Add standard and extension version to the package names that reference EdFi.Ods.Standard project (#691)

* Add standard and extension version to the package names that reference EdFi.Ods.Standard project

* StandardVersions function updated

* Build name added with Standard Version

* [ODS-5766] Add the Standard version to the minimal and populated templates (#692)

* Modified postgres builds to support multiple standard versions

* Modified mssql builds to support multiple standard versions

* revert push branches

* Fixed sintax error

* reverted push branches

* [ODS-5767] Add the Standard version to packages that reference Ed-Fi-TPDM-Artifacts repository (#694)

* Modified postgresql builds to support multiple standard versions

* Fixes issue in CodeGen that was setting a wrong assembly name on the extensio EntityOrmMapping files

* Modified mssql builds to support multiple standard versions

* Revert build execution on ODS-* branch push

* [ODS-5795] Shorten CodeGen approval test files (#697)

* Removed old unused approved files

* Shortened the approval file names

* [ODS-5796] Modify builds to support multiple standard versions (#699)

* Added standard version to database admin packages

* Added standard version to database security packages

* Shorten build name

---------

Co-authored-by: semalaiappan <34613894+semalaiappan@users.noreply.github.com>

diff --git a/.github/workflows/Pkg EdFi.Database.Admin.yml b/.github/workflows/Pkg EdFi.Database.Admin.yml
--- a/.github/workflows/Pkg EdFi.Database.Admin.yml
+++ b/.github/workflows/Pkg EdFi.Database.Admin.yml
@@ -30,14 +30,60 @@ env:
   REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
+
+  FindStandardAndExtensionVersions:
+     runs-on: ubuntu-latest
+     outputs:
+       StandardVersions: ${{ steps.Set_StandardVersions.outputs.StandardVersions }}
+       ExtensionVersions: ${{ steps.Set_ExtensionVersions.outputs.ExtensionVersions }}
+     steps:
+     - name: Checkout Ed-Fi-ODS
+       uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
+       with:
+           repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
+           path: Ed-Fi-ODS/
+     - name: Checkout Ed-Fi-Extensions
+       uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
+       with:
+          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Extensions
+          path: Ed-Fi-Extensions/
+     - name: Is pull request branch exists in Ed-Fi-Extensions
+       working-directory: ./Ed-Fi-ODS/
+       shell: pwsh
+       run: |
+         .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath "../Ed-Fi-Extensions"
+     - name: Set StandardVersions
+       id: Set_StandardVersions
+       working-directory: ./Ed-Fi-ODS/
+       run: |
+         $output = .\build.githubactions.ps1 StandardVersions -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"
+         echo "StandardVersions=$output" >> $env:GITHUB_OUTPUT
+         Write-host "StandardVersions is  $output"
+       shell: pwsh
+     - name: Set ExtensionVersions
+       id: Set_ExtensionVersions
+       working-directory: ./Ed-Fi-Extensions/
+       run: |
+         $output = .\build.githubactions.ps1 ExtensionVersions -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM/EdFi.Ods.Extensions.TPDM.csproj"
+         echo "ExtensionVersions=$output" >> $env:GITHUB_OUTPUT
+         Write-host "ExtensionVersions is  $output"
+       shell: pwsh
+
   build:
-
+    if: ${{ always() }}
+    needs: FindStandardAndExtensionVersions
     runs-on: windows-latest
-
+    strategy:
+      matrix:
+        StandardVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.StandardVersions) }}
+        ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
+    name: build (${{ matrix.StandardVersion }}, ${{ matrix.ExtensionVersion }})
     steps:
     - name: Check for Azure token
       if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
-      run: exit 1 
+      run: | 
+        echo "::error::Missing Azure Token"
+        exit 1 
     - name: Setup .NET
       uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # v2.1.0
       with:
@@ -78,7 +124,7 @@ jobs:
       run: |
           $ErrorActionPreference = 'Stop'
           $PSVersionTable
-          . $env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/logistics/scripts/activities/build/create-database-package.ps1 -Output NugetPackages -DatabaseType Admin  -SQLPackage "C:\ProgramData\chocolatey\lib\sqlpackage\tools"
+          . $env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/logistics/scripts/activities/build/create-database-package.ps1 -Output NugetPackages -DatabaseType Admin -ExtensionVersion ${{ matrix.ExtensionVersion }} -StandardVersion ${{ matrix.StandardVersion }} -SQLPackage "C:\ProgramData\chocolatey\lib\sqlpackage\tools"
     - name: Use NuGet
       uses: nuget/setup-nuget@b2bc17b761a1d88cab755a776c7922eb26eefbfa # v1
       with:
@@ -91,9 +137,9 @@ jobs:
         [int]$newRevision =  $BuildCounter + $BuildIncrementer
         [string]$version = "${{env.INFORMATIONAL_VERSION}}"+ "." + $newRevision.ToString()
         $packageOutput = "$env:GITHUB_WORKSPACE/Ed-Fi-ODS/NugetPackages"
-        $AdminNuspecFilePath = "$env:GITHUB_WORKSPACE/NugetPackages/EdFi.Database.Admin.nuspec"
-        $AdminBACPACNuspecFilePath = "$env:GITHUB_WORKSPACE/NugetPackages/EdFi.Database.Admin.BACPAC.nuspec"
-        $AdminPostgreSQLNuspecFilePath = "$env:GITHUB_WORKSPACE/NugetPackages/EdFi.Database.Admin.PostgreSQL.nuspec"
+        $AdminNuspecFilePath = "$env:GITHUB_WORKSPACE/NugetPackages/EdFi.Database.Admin.Standard.${{ matrix.StandardVersion }}.nuspec"
+        $AdminBACPACNuspecFilePath = "$env:GITHUB_WORKSPACE/NugetPackages/EdFi.Database.Admin.BACPAC.Standard.${{ matrix.StandardVersion }}.nuspec"
+        $AdminPostgreSQLNuspecFilePath = "$env:GITHUB_WORKSPACE/NugetPackages/EdFi.Database.Admin.PostgreSQL.Standard.${{ matrix.StandardVersion }}.nuspec"
         nuget pack $AdminNuspecFilePath -OutputDirectory $packageOutput -Version $version -Properties "configuration=release" -Properties "authors=Ed-Fi Alliance" -Properties "owners=Ed-Fi Alliance" -Properties "copyright=Copyright © $(date +'%Y') Ed-Fi Alliance, LLC and Contributors" -NoPackageAnalysis -NoDefaultExcludes
         nuget pack $AdminBACPACNuspecFilePath -OutputDirectory $packageOutput -Version $version -Properties "configuration=release" -Properties "authors=Ed-Fi Alliance" -Properties "owners=Ed-Fi Alliance" -Properties "copyright=Copyright © $(date +'%Y') Ed-Fi Alliance, LLC and Contributors" -NoPackageAnalysis -NoDefaultExcludes
         nuget pack $AdminPostgreSQLNuspecFilePath -OutputDirectory $packageOutput -Version $version -Properties "configuration=release" -Properties "authors=Ed-Fi Alliance" -Properties "owners=Ed-Fi Alliance" -Properties "copyright=Copyright © $(date +'%Y') Ed-Fi Alliance, LLC and Contributors" -NoPackageAnalysis -NoDefaultExcludes
@@ -104,12 +150,12 @@ jobs:
       if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       working-directory: ./Ed-Fi-ODS/
       run: |
-        ./build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -PackageName  "EdFi.Database.Admin"
-        ./build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -PackageName  "EdFi.Database.Admin.BACPAC"
-        ./build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -PackageName  "EdFi.Database.Admin.PostgreSQL"
+        ./build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -PackageName  "EdFi.Database.Admin.Standard.${{ matrix.StandardVersion }}"
+        ./build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -PackageName  "EdFi.Database.Admin.BACPAC.Standard.${{ matrix.StandardVersion }}"
+        ./build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -PackageName  "EdFi.Database.Admin.PostgreSQL.Standard.${{ matrix.StandardVersion }}"
     - name: Upload EdFi.Database.Admin Artifacts
       if: success()
       uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
       with:
         name: NugetPackages.Artifacts
-        path: ${{ github.workspace }}/NugetPackages/*.nupkg
+        path: ${{ github.workspace }}/Ed-Fi-ODS/NugetPackages/*.nupkg
